### ISSUE TITLE
Add Power BI Report Server mode!

### ISSUE THREAD

**Issue by diegouchoa** [PicolotoLF/SlideShowPowerBI#1]
Hi/Oi,

Is possible add a Power BI Report Server mode?/É possível adicionar as mesmas funcionalidades para o Power BI Report Server?

**Comment by PicolotoLF** [comment]
@diegouchoa 
I have never worked with Report Server ... But this is a extension of Chrome, so if you show your reports in Google Chrome, this extension will help you.
