### ISSUE TITLE
does not display

### ISSUE THREAD

**Issue by Avengerjrob** [PicolotoLF/SlideShowPowerBI#2]
i have followed all the instructions and when i click the icon a message pulls up in Portuguese stating it cannot be displayed? any insight

**Comment by PicolotoLF** [comment]
@Avengerjrob 
This error occur when you are not in the report page.
To work you should be in the report page 

like this:
![image](https://user-images.githubusercontent.com/23582642/39277094-80a0d28a-48c2-11e8-9e47-1485b66e268b.png)

**Comment by Avengerjrob** [comment]
I did not realize this. You are correct sir thanks for this.
